### PR TITLE
Collaterals translation

### PR DESCRIPTION
**Pull request by Omar-Nabil**
adding the translation for src/products/collaterals , changes in translation files was adding "Edit": "Edit" inside "text" so it can be used inside breadcrumb while editing the collaterals and "Base Percentage" because it wasn't exist

### CODE REVIEW

**Comment by Omar-Nabil** [comment]
@alberto-art3ch

**Comment by PC-11-00** [comment]
@Omar-Nabil There are rules of contributing and you should follow those guideline rules:  https://github.com/openMF/web-app/blob/8bee3f2f51014794d12febd0093940bdd3e2ba27/.github/CONTRIBUTING.md
And also follow PR template

**Comment by Omar-Nabil** [comment]
@PC-11-00  i read already and i can't find where is the problem i flowed this all steps except the screen shot, is it the problem ?

**Comment by PC-11-00** [comment]
The PR should look like this: https://github.com/openMF/web-app/pull/2030
PR Template: https://github.com/openMF/web-app/blob/8bee3f2f51014794d12febd0093940bdd3e2ba27/.github/PULL_REQUEST_TEMPLATE.md
Commit Message Convention: https://github.com/openMF/web-app/blob/8bee3f2f51014794d12febd0093940bdd3e2ba27/.github/COMMIT_MESSAGE.md

**Pull request closed without merging**
