### PR TITLE
refactor (df/locale): loans module

### PR DESCRIPTION
**Pull request by shobhi1310**
## Description
Added centralized dates format and languages in loans module

## Related issues and discussion
#1213

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] If you have multiple commits please combine them into one commit by squashing them.

- [x] Read and understood the contribution guidelines at `web-app/.github/CONTRIBUTING.md`.

### CODE REVIEW

**Comment by shobhi1310** [comment]
@karantakalkar 
Sir, do review my PR once.

**Comment by shobhi1310** [comment]
@karantakalkar 
Sir, please do review my PR once, as it could count towards Hacktober fest if merged.

**Comment by karantakalkar** [comment]
I have labelled it and it counts towards HF as per new rules.

**Comment by shobhi1310** [comment]
Sir, but in my number of PRs towards hacktober fest it is not counting it, I think it also needs to be merges I guess. 🤔

**Review by karantakalkar — APPROVED** [review]

**Pull request merged**
