### PR TITLE
fix: position for tooltip on sidenavbar located on home

### PR DESCRIPTION
**Pull request by kunjgit**
## Description

MatTooltip position is needed to be changed to solve this issue in ui .

## Related issues and discussion

#1955

## Screenshots, if any
image

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] If you have multiple commits please combine them into one commit by squashing them.

- [x] Read and understood the contribution guidelines at `web-app/.github/CONTRIBUTING.md`.

### CODE REVIEW

**Comment by kunjgit** [comment]
@PC-11-00 ! have a look :eyes: 
PopUp keeping it in another PR as it's totally different ..

**Comment by PC-11-00** [comment]
Only one commit should be made, so please squash the commits

**Comment by kunjgit** [comment]
@PC-11-00 few changes made afterwards ! :smile: 
should I squash them all :question: 
I have squashed my two commits in one ..

**Comment by PC-11-00** [comment]
Yeah one PR - one commit and also remove env.ts file changes

**Comment by kunjgit** [comment]
@PC-11-00 here you go :smile: !

**Comment by PC-11-00** [comment]
You haven't pulled the changes from the openMF in your forked repo , because I can see there are files changes in 18 files which were made by me and Alberto in your PR

**Comment by kunjgit** [comment]
@PC-11-00 both the branches are up to dated the issue is after I made changes those changes are added !

**Comment by PC-11-00** [comment]
@kunjgit you need to remove the changes from your forked repo and then you need to merge the changes to your repo and then you ned to use merging from your repo to your local using git merge and git pull concept.

**Pull request closed without merging**
