### PR TITLE
feat: add standing instruction component

### PR DESCRIPTION
**Pull request by IgorWilbert**
## Description
Added the "Create Standing Instruction" component in the format requested.

## Related issues and discussion
#268 

## Screenshots, if any
capture

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [X] If you have multiple commits please combine them into one commit by squashing them.

- [X] Read and understood the contribution guidelines at `web-app/.github/CONTRIBUTING.md`.

### CODE REVIEW

**Comment by abhaychawla** [comment]
@IgorWilbert Its not possible to review the PR until you remove all the prior commits.

**Comment by abhaychawla** [comment]
@IgorWilbert At first glance, I see that you'll have to update your code as well. You need to use reactive forms and also the UI need to be updated. I see you have not implemented the functionality as well. Please take reference from accounting section and update this PR.

**Comment by IgorWilbert** [comment]
@abhaychawla sorry for taking so long to answer. Yes, please if you could help me with Git it would be great. I am able to remove the file of the other PR with 'amend', but I don't know what to do from there. I will see what I can do about the UI.

**Comment by abhaychawla** [comment]
@IgorWilbert What problem are you facing?

**Comment by abhaychawla** [comment]
@IgorWilbert Open the developer tools of the browser you are using and check the console for errors when you run the application. Apart from that as I already told you above please take a look at accounting section for reference regarding the UI and functionality, not the clients section the code of clients section is obsolete and needs to be updated.

**Comment by jonathanzhang53** [comment]
Travis CI is having some errors too. See [here](https://travis-ci.com/openMF/web-app/builds/93446511) for the build errors.

Abhay wants you to squash your commits for cleaner PRs. He has a guide somewhere. Aha [here](https://github.com/openMF/web-app/blob/master/.github/CONTRIBUTING.md#configuring-remotes)

**Comment by abhaychawla** [comment]
I didn't say that you shouldn't create additional files, you'll have to create the necessary files for the implementation of the component. You should create resolvers if required. Kindly do not comment on the PR and then tag me on gitter as well, I receive multiple notifications unnecessarily. Tagging me at multiple places doesn't mean that you'll get a faster reply.

**Comment by abhaychawla** [comment]
Closing this PR due to a long period of inactivity.

**Pull request closed without merging**
