### PR TITLE
Issue1317

### PR DESCRIPTION
**Pull request by gustavao**
## Description
Hi, I found the problem adding the correct route

## Related issues and discussion
#{Issue 1317}

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] If you have multiple commits please combine them into one commit by squashing them.

- [ ] Read and understood the contribution guidelines at `web-app/.github/CONTRIBUTING.md`.

### CODE REVIEW

**Comment by bharathcgowda** [comment]
@BLasan  @spider0061  can you help with the code review please? @gustavao  could you check why all the checks have failed

**Comment by gustavao** [comment]
> @BLasan @spider0061 can you help with the code review please? @gustavao could you check why all the checks have failed

Of course, it is already solved, it was an alignment issue

**Review by bharathcgowda — APPROVED** [review]
Functional working as expected. can be merged after code review

**Review by BLasan — APPROVED** [review]
LGTM!

**Pull request merged**
