### PR TITLE
feat: add Configure Maker Checker Tasks Component

### PR DESCRIPTION
**Pull request by manigedit**
## Description
Describe the changes made and why they were made instead of how they were made. List any dependencies that are required for this change.

## Related issues and discussion
#184 

## Screenshots, if any
maker-checker

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [* ] If you have multiple commits please combine them into one commit by squashing them.

- [ *] Read and understood the contribution guidelines at `web-app/.github/CONTRIBUTING.md`.

### CODE REVIEW

**Comment by manigedit** [comment]
Could you please re run the CI build. It should pass (it was passing last time until I just fixed a typo in the docs) idk, why did it take more than 14  minutes while building but didn't throw any error.

**Comment by karantakalkar** [comment]
@manigedit considering community app UI shouldn't this be implemented similar to https://github.com/openMF/web-app/pull/632 ?

**Comment by abhaychawla** [comment]
@manigedit As discussed earlier, lets update this PR and use list to maintain consistency. Also, use x in the checklist to get a tick mark sign instead of * (asterisk).

**Comment by karantakalkar** [comment]
@manigedit If you won't get time to update let us know.

**Comment by BLasan** [comment]
@karantakalkar Can I work on this?

**Comment by muskankhedia** [comment]
Sure. Refer to PR #632 for UI purposes.

**Comment by BLasan** [comment]
> Sure. Refer to PR #632 for UI purposes.

Sure

**Comment by karantakalkar** [comment]
Closing, will be worked on in GSoC phase 1.

**Pull request closed without merging**
