### PR TITLE
test: initialize e2e-testing with login page

### PR DESCRIPTION
**Pull request by karantakalkar**
## Description
Before running `ng e2e` kindly update your local webriver manager by running

`$ ./node_modules/protractor/bin/webdriver-manager update`

Jasmine and all scripts loading timeout have been changed to accommodate for large initial loading time. 

## Related issues and discussion
#697

## Screenshots, if any
Screenshot from 2020-03-28 18-00-56

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] If you have multiple commits please combine them into one commit by squashing them.

- [x] Read and understood the contribution guidelines at `web-app/.github/CONTRIBUTING.md`.

### CODE REVIEW

**Comment by karantakalkar** [comment]
@muskankhedia Please review this

**Comment by muskankhedia** [comment]
@karantakalkar Presently, there is no finalised decision on testing tools that will be used. And this being a critical topic for now and future, it also needs discussion with the senior mentors for the decision. And also none of the mentors have reviewed it yet. I don't see any use of this PR to be merged from now.
@abhaychawla Can you please have a look?

**Comment by karantakalkar** [comment]
anyways its only refactoring.

**Comment by muskankhedia** [comment]
And so it's not required.

**Comment by karantakalkar** [comment]
I can't un-merge this even if it's useless.

**Comment by muskankhedia** [comment]
It can be reverted but let that be for now. For such decisions, we need to wait for mentors to approve it or at least review them. That will help us make better decisions.

**Comment by abhaychawla** [comment]
@karantakalkar @muskankhedia Its alright for the time being. Lets just focus on the rewrite for now, we can decide on testing once we have made a significant progress.

**Pull request merged**
