### PR TITLE
Change language dropdown json to be in native languages (#;2C1958)

### PR DESCRIPTION
**Pull request by liaozhuzhu**
## Description
Changed all `*.json` files in `src/translations` to keep the native languages consistent across all languages.

## Related issues and discussion
#1958 

## Screenshots, if any
**Before / After**

Screen Shot 2024-01-06 at 5 57 42 PM
Screen Shot 2024-01-06 at 5 58 03 PM

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [X] If you have multiple commits please combine them into one commit by squashing them.

- [X] Read and understood the contribution guidelines at `web-app/.github/CONTRIBUTING.md`.

### CODE REVIEW

**Comment by PC-11-00** [comment]
Please read the contribution guidelines for making PR and issues : https://github.com/openMF/web-app/blob/master/.github/CONTRIBUTING.md

**Comment by liaozhuzhu** [comment]
@PC-11-00 thanks for the heads up. I've already read the cont. guidelines and believe I've followed all the steps. Is there something specifically that I'm missing?

**Comment by PC-11-00** [comment]
Yes , and two checks are not ticked properly. Commit message should also follow this template: https://github.com/openMF/web-app/blob/master/.github/COMMIT_MESSAGE.md

**Comment by liaozhuzhu** [comment]
Oh you're totally right. Okay thank you for catching that I'll be sure to fix it soon!

**Comment by liaozhuzhu** [comment]
- Removed random space from checklist
- Git commit message has been updated per [commit documentation](https://github.com/openMF/web-app/blob/master/.github/COMMIT_MESSAGE.md)

Thank you @PC-11-00 <3

**Pull request closed without merging**
