### PR TITLE
Mifos user creation fails with no error message #1795

### PR DESCRIPTION
**Pull request by Thanush66**
Mifos user creation fails with no error message #1795 

this issue solved

### CODE REVIEW

**Comment by PC-11-00** [comment]
please follow the contribution guideline before making any pull request : https://github.com/openMF/web-app/blob/8bee3f2f51014794d12febd0093940bdd3e2ba27/.github/COMMIT_MESSAGE.md

**Comment by Thanush66** [comment]
Could you please help me how can I do it . I am new to open source I saw your GitHub profile. It  was awesome. Tell me how can I do open source and make good contributions.  Thank you for mailing me!. From: pc_11Sent: 31 July 2023 07:48To: openMF/web-appCc: Thanush66; AuthorSubject: Re: [openMF/web-app] Mifos user creation fails with no error message #1795 (PR #1832) please follow the contribution guideline before making any pull request : https://github.com/openMF/web-app/blob/8bee3f2f51014794d12febd0093940bdd3e2ba27/.github/COMMIT_MESSAGE.md—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by Thanush66** [comment]
could please help me with that?

**Comment by bharathcgowda** [comment]
@josehernandezfintecheandomx  @adamsaghy  could you please help me in reviwing this PR?

**Pull request closed without merging**
