### PR TITLE
Fix : Updated shortcut keymap to make it work on all browsers and OS .

### PR DESCRIPTION
**Pull request by kunjgit**
## Description
Changed shortcuts keymap to make it work for all kind of OS and without having browser defaults issues 

## Related issues and discussion

#2012 

## Screenshots, if any

https://github.com/openMF/web-app/assets/103763618/3ce4dc4a-edf5-4915-9b4c-40833427dc12

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] If you have multiple commits please combine them into one commit by squashing them.

- [x] Read and understood the contribution guidelines at `web-app/.github/CONTRIBUTING.md`.

### CODE REVIEW

**Comment by kunjgit** [comment]
@PC-11-00 have a look at the solution we can have !
tell me if anything requires to be one .
`event.preventDefault()` is not working so the only possible way we have is setting keybinding such it's feasible at everywhere !

**Comment by kunjgit** [comment]
@PC-11-00 done with linting fix 👀 !

**Comment by PC-11-00** [comment]
LGTM!

**Review by PC-11-00 — APPROVED** [review]

**Comment by kunjgit** [comment]
@alberto-art3ch is there anything to be updated !?

**Review by alberto-art3ch — APPROVED** [review]
LGTM

**Pull request merged**
