### PR TITLE
edit-fix-local-login solved: #701

### PR DESCRIPTION
**Pull request by Aaryan-kapur**
## Description
Edited environment.ts
This solves login in a local environment
## Related issues and discussion
#701

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] If you have multiple commits please combine them into one commit by squashing them.

- [x] Read and understood the contribution guidelines at `web-app/.github/CONTRIBUTING.md`.

Important instructions 
For Windows:

> 
> Open the start menu
> Type windows+R or open "Run"
> Execute the following command:
> 
> chrome.exe --user-data-dir="C://Chrome dev session" --disable-web-security

For Mac:

> 
> Go to Terminal
> Execute the following command:
> 
> open /Applications/Google\ Chrome.app --args --user-data-dir="/var/tmp/Chrome dev session" --disable-web-security

### CODE REVIEW

**Comment by karantakalkar** [comment]
already fixed by: #667

**Comment by karantakalkar** [comment]
@Aaryan-kapur #701 is a different issue, it is with regard to connecting web app with the local instance of apache fineract

**Comment by Aaryan-kapur** [comment]
@karantakalkar sir! this issue is also resolved when you follow the steps mentioned!
I had been getting CORS errors too but if you follow all the steps it will work properly sir!

**Comment by abhaychawla** [comment]
Closing, as this is a duplicate of #667

**Pull request closed without merging**
