### PR TITLE
wip: feat: add reports component

### PR DESCRIPTION
**Pull request by jonathanzhang53**
# This PR is a Work in Progress

## Description
Added reports component.

## Related issues and discussion
#232 

## Screenshots, if any
Not Available now

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] If you have multiple commits please combine them into one commit by squashing them.

- [x] Read and understood the contribution guidelines at `web-app/.github/CONTRIBUTING.md`.

### CODE REVIEW

**Comment by jonathanzhang53** [comment]
Hi @abhaychawla I made this PR as a wip pr so that I could ask questions. Currently, I have set up routerlink to `/reports` when you click `Reports > All`, and I have configured `reports.routing.module.ts` similar to `accounting.routing.module.ts`, but there is a 404 page when I click `Reports > All` with this code.

The url I get is `http://localhost:4200/reports`

**Comment by abhaychawla** [comment]
@jonathanzhang53 If you are still working on this, please update your PR or it will be closed due to inactivity.

**Comment by jonathanzhang53** [comment]
Sorry @abhaychawla school has been busy so I have not had time to work on PRs. I will close for now.

**Comment by abhaychawla** [comment]
No issues.

**Pull request closed without merging**
