### PR TITLE
refactor: following American Eng conventions by default

### LINKED ISSUE #330: Organisation Spelling to American Organization
## Description
American English spelling is 'organization'. This may be a better fit for the app.

## Steps to Reproduce
Log into web app.
Under admin menu on the top tool bar, select and look at `organisation` title.

## Expected Behaviour
'organization'

## Actual Behaviour
'organisation'

## Screenshots, if any
image

### PR DESCRIPTION
**Pull request by jonathanzhang53**
## Description
Changed all instances of 'organisation' to 'organization'

## Related issues and discussion
#330 

## Screenshots, if any
image

## Checklist

- [x] If you have multiple commits please combine them into one commit by squashing them.

- [x] Read and understood the contribution guidelines at `web-app/.github/CONTRIBUTING.md`.

### CODE REVIEW

**Comment by abhaychawla** [comment]
@jonathanzhang53 Changes look okay. After discussion, we have decided to follow American English conventions as default for the web-app. As we saw earlier, organisation isn't a misspelling but only an alternate spelling used sometimes within British English. I need you to update your issue, PR description and commit message to reflect that accordingly. Also, don't mention the word `Fixes or Closes` within the PR description. Make sure you follow the guidelines(format) of the commit message. As this isn't a bug your commit message should be something like this:

```
refractor: follow American English conventions by default

* Change organisation to organization

Closes: #330 
```

**Comment by jonathanzhang53** [comment]
@abhaychawla Thank you. Fixed.

Although I do wonder, why not put fixes or closes in the description? I have created an issue for this and it should close along with the PR, correct?

**Comment by abhaychawla** [comment]
You cannot use `following` or `changed`. Use the imperative, present tense only.
https://github.com/openMF/web-app/blob/master/.github/COMMIT_MESSAGE.md

As we already put Fixes or Closes within the commit message which closes the issue on merging the PR we do not need that keyword in the description.

**Comment by abhaychawla** [comment]
There is still an issue with the tense. Your commit message shows `changed`. Also, do not use the short form for English.

**Pull request merged**
