### PR TITLE
refactor: loans-general-tab & loans-transactions-tab

### PR DESCRIPTION
**Pull request by BLasan**
## Description
Refactored the General Tab & Transaction Tab UIs in Clients-Loans page.

## Related issues and discussion
#1249 

## Screenshots, if any
Screenshot from 2020-10-22 12-14-15
Screenshot from 2020-10-22 12-30-32

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] If you have multiple commits please combine them into one commit by squashing them.

- [x] Read and understood the contribution guidelines at `web-app/.github/CONTRIBUTING.md`.

### CODE REVIEW

**Comment by BLasan** [comment]
@karantakalkar Please review

**Comment by karantakalkar** [comment]
Can you make it consistent with savings account view page ? We need a bit precise refinement here.

**Comment by bharathcgowda** [comment]
Hi @BLasan  did you get a chance to make the changes as per the latest comment to this PR?

**Comment by BLasan** [comment]
> Hi @BLasan did you get a chance to make the changes as per the latest comment to this PR?

Hi, actually didn't get a chance to do so

**Comment by bharathcgowda** [comment]
@no worries @BLasan  we can have a look after the GSOC work is complete :)

**Comment by avikganguly01** [comment]
@karantakalkar  @bharathcgowda @BLasan  : We are reviewing the Angular 13 PR. I want to get mergeable PRs merged into Web App before that.

Is this something that can be pulled in or needs further enhancements to make it mergeable?

**Pull request closed without merging**
