### PR TITLE
Added Tooltips to Create Recurring Deposit screens

### PR DESCRIPTION
**Pull request by radhathakare**
## Description
Added Tooltips to Create Recurring Deposit screens

## Related issues and discussion
#1672 

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] If you have multiple commits please combine them into one commit by squashing them.

- [ ] Read and understood the contribution guidelines at `web-app/.github/CONTRIBUTING.md`.

### CODE REVIEW

**Comment by radhathakare** [comment]
[
Screenshot (23)
[](url)](
Screenshot (24)
)

**Comment by PC-11-00** [comment]
@radhathakare This is not a tooltip that you implemented, tooltips are the description of the label and that help to understand the functionality of the label, this is not like , you can write the name of the label in tooltip

**Comment by radhathakare** [comment]
> @radhathakare This is not a tooltip that you implemented, tooltips are the description of the label and that help to understand the functionality of the label, this is not like , you can write the name of the label in tooltip

@PC-11-00 Yes, I have made recommended changes.

**Comment by radhathakare** [comment]
> > @radhathakare This is not a tooltip that you implemented, tooltips are the description of the label and that help to understand the functionality of the label, this is not like , you can write the name of the label in tooltip
> 
> @PC-11-00 Yes, I have made recommended changes.
Thank You

**Comment by bharathcgowda** [comment]
@josehernandezfintecheandomx can you please review the PR?

**Pull request closed without merging**
