### PR TITLE
Solution for TranslateModule not exported from SharedModule #1304

### PR DESCRIPTION
**Pull request by nestorlazcano-fintecheando**
## Description
Fixed implementation of translated because it is not working correctly

## Related issues and discussion
#1304

### English 

image

### French 

image

### CODE REVIEW

**Comment by Jov03** [comment]
@nestorlazcano-fintecheando linting errors still exist which are causing git hub's build to fail. To check linting errors locally you can run `ng lint` on your local system. Also, your PR still contains multiple commits, please squash them into a single commit as mentioned in contributing guidelines.

https://github.com/openMF/web-app/blob/master/.github/CONTRIBUTING.md#submitting-a-pull-request

**Comment by nestorlazcano-fintecheando** [comment]
@Jov03 Thanks for your help, I solved the issues

**Comment by Jov03** [comment]
@nestorlazcano-fintecheando great. Now please squash the commits into a single commit as mentioned in contributing guidelines.    Refer to the link shared in the previous comment.

**Comment by bharathcgowda** [comment]
@nestorlazcano-fintecheando  did you get a chance to send it as a single commit as suggested by @Jov03

**Comment by nestorlazcano-fintecheando** [comment]
@Jov03 Done

**Pull request merged**
