### PR TITLE
feat: add adhoc query component

### PR DESCRIPTION
**Pull request by punwai**
## Description
- Add Adhoc Query component

## Related issues and discussion
#511

## Screenshots, if any
Adhoc Query
ahlist

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] If you have multiple commits please combine them into one commit by squashing them.

- [x] Read and understood the contribution guidelines at `web-app/.github/CONTRIBUTING.md`.

### CODE REVIEW

**Comment by punwai** [comment]
Linting has passed but Travis CLI keeps failing because of timeout. I will keep checking this when I can and keep re pushing until it works, but there should be no errors within the file if that is enough for you.

**Comment by punwai** [comment]
Report run frequency appears as a code because the 'reportRunFrequency.value' property of the object returned in the API is incorrectly returned as a code. In all other API endpoints, value returns a word that can be used as a label. To ensure consistency, I believe that the code should be kept as is, but we should contact somebody working on the API to make a quick change to this specific endpoint. This should not be a problem because I have checked and reportRunFrequency.value is not used in the community app.

**Comment by abhaychawla** [comment]
@punwai Can you check at https://issues.apache.org/jira/projects/FINERACT/issues if there is an existing issue for this? If there isn't then please create it.

**Comment by punwai** [comment]
@abhaychawla https://issues.apache.org/jira/browse/FINERACT-818 Ticket created.

**Pull request merged**
