### PR TITLE
Replace Material Icons by Angular Font Awesome Icons

### PR DESCRIPTION
**Pull request by love-opensource**
Replace the material icons to angular font awesome in 3 files; Clients, Groups and Centers

### CODE REVIEW

**Comment by abhaychawla** [comment]
@love-opensource Why are there two commits in your PR that too from two different accounts and why have you not followed the Pull Request Template?

**Comment by love-opensource** [comment]
@abhaychawla That happened because I had another github account that was saved in my computer and I changed the credentials which only limited to cmd but the pull request sent in my next account. But I successfully removed that account.

**Comment by abhaychawla** [comment]
@love-opensource Update this PR with a single commit from your account only. Follow the commit guidelines and PR template. After you do this, then only I would be able to review your PR.

**Comment by santoshconflux** [comment]
@love-opensource , May I know the ticket id for this? Make sure ticket is raised for any  PR being sent.

**Pull request closed without merging**
