### PR TITLE
feat English Json File

### PR DESCRIPTION
**Pull request by radhathakare**
## Description
Describe the changes made and why they were made instead of how they were made. List any dependencies that are required for this change.

## Related issues and discussion
#{Issue Number}

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] If you have multiple commits please combine them into one commit by squashing them.

- [ ] Read and understood the contribution guidelines at `web-app/.github/CONTRIBUTING.md`.

### CODE REVIEW

**Comment by adamsaghy** [comment]
@radhathakare Hi
Sorry for the late reaction. Would you mind to resolve the conflicts on your PRs? We would be happy to have them! :)

**Comment by radhathakare** [comment]
Hi
@adamsaghy I will work on it and let you know.

**Comment by radhathakare** [comment]
Hi @adamsaghy I have resolved conflicts please have a look.

**Comment by adamsaghy** [comment]
@radhathakare Please check it again. It says, it is still has conflicts

**Pull request closed without merging**
