### PR TITLE
feat: add groups view page (general-tab)

### PR DESCRIPTION
**Pull request by karantakalkar**
## Description

- Developed the view group page header.
- Developed group's general tab.
- Connected client members to respective clients view page.
- Added tool-tips throughout the page.
- Made action buttons tab conditional taking reference from community app code.
- Made all tables conditional ie: will only be shown if data is available.
- Enforced permissions using has permission directive.

## Related issues and discussion
#217 

## Screenshots, if any

**Example 1**

Screenshot from 2020-05-20 13-21-34

**Example 2**

Screenshot from 2020-05-20 13-22-48

**Example 3**

Screenshot from 2020-05-20 13-23-17

**Sample Test Case:** "123AAkee"
## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] If you have multiple commits please combine them into one commit by squashing them.

- [x] Read and understood the contribution guidelines at `web-app/.github/CONTRIBUTING.md`.

### CODE REVIEW

**Comment by muskankhedia** [comment]
@karantakalkar Can you have a check, the action buttons displayed in the web-app are different from the community app for the same group. Also, add the buttons with the client members section.

**Comment by karantakalkar** [comment]
@muskankhedia I have shifted client members buttons to action buttons tab that's why they appear different.

**Comment by muskankhedia** [comment]
Yaa i did get that. I am talking about the buttons such as `Transfer Client`, `Manage Members` and `Add` button as shown in the picture below:
Screenshot from 2020-05-20 14-30-57

**Comment by karantakalkar** [comment]
Have a look at screenshots they are in action buttons tab

**Pull request merged**
