### PR TITLE
feat(product): translate collaterals folder and add missing translations

### PR DESCRIPTION
**Pull request by Omar-Nabil**
## Description
Translated all HTML files within the collaterals folder under the product module. Utilized TranslateService for the translation process. Additionally, added the missing translation 'Edit' to each JSON file within the translation folder. Also, included 'Base Percentage' in each JSON file as it was not found in the existing translations.

This commit enhances the internationalization of the product module, ensuring a more comprehensive localization for [users.]

https://github.com/openMF/web-app/assets/113044700/3a9804bc-8142-4197-8c6b-31a6e1fe230f

- [ done] If you have multiple commits please combine them into one commit by squashing them.

- [ done] Read and understood the contribution guidelines at `web-app/.github/CONTRIBUTING.md`.

### CODE REVIEW

**Comment by Omar-Nabil** [comment]
@adamsaghy @PC-11-00  i read this https://github.com/openMF/web-app/blob/8bee3f2f51014794d12febd0093940bdd3e2ba27/.github/COMMIT_MESSAGE.md and flowed all the steps if there is some thing wrong please tell me

**Comment by PC-11-00** [comment]
Checks should be ticked like [x]

**Review by PC-11-00 — APPROVED** [review]
LGTM!

**Review by alberto-art3ch — APPROVED** [review]
LGTM

**Pull request merged**
