### PR TITLE
feat: create fd account application page

### PR DESCRIPTION
**Pull request by abhi40308**
## Description
Added FD application page for creating New fixed deposit account. 
* Add Deposits Module (taking reference from community app).
* Add Deposits Routing and Deposits Service.
* Add NewFixedDeposit Component.
* Add New Fixed Deposit Resolver.
* Add Show Incentives Dialog Component (for incentives model/dialog in Interest Rate Chart Table).
* Add Edit Charge Dialog Component (for editing charges in Charge Table).
 

## Related issues and discussion
#226 

## Demo
[See demo for FD account application page](https://www.youtube.com/watch?v=RXZGtbP6WF8)
Edit: [Updated demo](https://www.youtube.com/watch?v=Yd_MDaKfZXc)

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [X] If you have multiple commits please combine them into one commit by squashing them.

- [X] Read and understood the contribution guidelines at `web-app/.github/CONTRIBUTING.md`.

### CODE REVIEW

**Comment by abhi40308** [comment]
build error due to timeout

**Comment by karantakalkar** [comment]
@abhi40308 phenomenal effort hats off! just use reactive forms instead of template driven forms.

**Comment by abhi40308** [comment]
@karantakalkar Thanks bro! I will look into this again once I finalize my proposal. Actually I thought and researched a lot about trying not to use `ngModel` before doing it, here it's a very complex use case which will probably make the code very clumsy if done pure reactive way.

**Comment by abhi40308** [comment]
@karantakalkar Removed the dependency on `ngModel`, instead created a separate dialog which takes care of editing charge data in table.

**Comment by abhi40308** [comment]
@abhaychawla  I have created this as a single page form ([demo](https://www.youtube.com/watch?v=Yd_MDaKfZXc)), as it is in the community app (https://demo.mifos.io/#/newclientfixeddepositaccount/1), but it can be implemented as a stepper component to keep it consistent with the other forms (`create-product` forms are done using stepper, and `create loan / savings` account will also be done as stepper https://demo.mifos.io/#/newclientloanaccount/1 ). Please share your views on this.

**Pull request closed without merging**
