### PR TITLE
fix: login to current versions of Fineract API (#741)

### PR DESCRIPTION
**Pull request by vorburger**
## Description
related to https://issues.apache.org/jira/browse/FINERACT-726

## Related issues and discussion
#741

## Screenshots, if any
NA

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] If you have multiple commits please combine them into one commit by squashing them.

- [x] Read and understood the contribution guidelines at `web-app/.github/CONTRIBUTING.md`.

### CODE REVIEW

**Comment by awasum** [comment]
@abhaychawla , What is holding this PR? I see people having problems logging in to the latest Fineract backend and this might fix their problems. FYI @vorburger

**Comment by abhaychawla** [comment]
@awasum I was waiting for an update to the staging server at https://staging.mifos.io which has been updated today. I am currently in discussion over mail about which development server to be used now as https://demo.mifos.io has not been updated yet. Once confirmed we will merge this PR (hopefully by the end of this week)

**Comment by awasum** [comment]
> @awasum I was waiting for an update to the staging server at https://staging.mifos.io which has been updated today. I am currently in discussion over mail about which development server to be used now as https://demo.mifos.io has not been updated yet. Once confirmed we will merge this PR (hopefully by the end of this week)

Thanks @abhaychawla

**Comment by awasum** [comment]
Have you seen this? https://www.fineract.dev/ which includes this UI: https://wui.fineract.dev/
That another demo environment if the other one is delaying. Just curious @vorburger  is this repo and the community app updated automatically on fineract.dev as each PR is merged? Just like on the backend repo? Just a thought. It will also help this project.

**Comment by abhaychawla** [comment]
@awasum Already aware about it. Currently waiting for confirmation from Ed if we should so Terence can setup a separate demo environment for us which has the latest code from Fineract to be used here instead.
The web app is hosted on gh-pages and updated with every PR that is merged.

**Comment by vorburger** [comment]
@abhaychawla @awasum I've created a new issue #786 to further discuss above, separate from this fix.

**Pull request merged**
