### PR TITLE
fix: frequent posting route in side-nav

### PR DESCRIPTION
**Pull request by BLasan**
## Description
Frequent Postings in side-nav routing resolved.

## Related issues and discussion
#731 

## Screenshots, if any
webapp5

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] If you have multiple commits please combine them into one commit by squashing them.

- [x] Read and understood the contribution guidelines at `web-app/.github/CONTRIBUTING.md`.

### CODE REVIEW

**Comment by BLasan** [comment]
@abhaychawla  Please review this

**Comment by maektwain** [comment]
Are there some tests for such scenario we should promote automated fixtures and test. We should not be dependent on the subjective reviews , machine are better judge of such things. Humans can and should do secondary testing.

What is your opinion , this could simply let us clear up clogged PR's

@vorburger

**Comment by abhaychawla** [comment]
@maektwain We plan to initiate automated testing this year with the help from GSoC students.

**Comment by BLasan** [comment]
> Thanks for the PR. But please update your commit message as per the guidelines. Use `imperative` tense. Do not begin your commit message with first character as uppercase.

Corrected the commit message. Please have a look

**Comment by karantakalkar** [comment]
@BLasan lowercase  'S' of Solve.

**Comment by BLasan** [comment]
> @BLasan all characters should be lowercase, also, in my opinion, a better commit message would be
> `fix: frequent posting route in side-nav`

Okay. I'll update it

**Pull request merged**
