### PR TITLE
activate holidays

### PR DESCRIPTION
**Pull request by gustavao**
## Description
Hi, I found the problem adding the request in the service

## Related issues and discussion
#{1315}

## Screenshots, if any
after
image
image

before
image

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] If you have multiple commits please combine them into one commit by squashing them.

- [x] Read and understood the contribution guidelines at `web-app/.github/CONTRIBUTING.md`.

### CODE REVIEW

**Comment by bharathcgowda** [comment]
Looks ok to me, @BLasan  could you help us by reviewing the code?
@gustavao  can you review why the checks have failed?

**Comment by gustavao** [comment]
> Looks ok to me, @BLasan could you help us by reviewing the code?
> @gustavao can you review why the checks have failed?

Of course, it is already solved, it was an alignment issue

**Review by bharathcgowda — APPROVED** [review]
Functional working as expected. can be merged after code review

**Review by Jov03 — CHANGES_REQUESTED** [review]
@gustavao your changes look good. Please squash your commits to a single commit so that we can merge this PR.

**Comment by bharathcgowda** [comment]
@Jov03  thank you for the review.
@gustavao  could you please send it as a single commit as requested please?

**Pull request merged**
