### PR TITLE
fix: edit charge - tax group is mandatory while creating charges

### PR DESCRIPTION
**Pull request by PC-11-00**
## Description
now it is mandatory to select tax-group to create charges in ui too, as it is in backend

## Related issues and discussion
#1722 
## Screenshots, if any

https://user-images.githubusercontent.com/76156941/228348869-3961165c-aeae-4590-93d6-67e4438b5644.mov

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] If you have multiple commits please combine them into one commit by squashing them.

- [x] Read and understood the contribution guidelines at `web-app/.github/CONTRIBUTING.md`.

### CODE REVIEW

**Comment by adamsaghy** [comment]
@PC-11-00 To be honest, we need exactly the opposite.

If there are existing tax groups, it can be selected on the charge view but it is not mandatory.

If no tax group was selected, the UI should not send any taxGroupId field in the request

**Comment by PC-11-00** [comment]
@adamsaghy okay, I understood wrong. One more doubt, if tax group is selected while creating the charges,are we allowed to change the tax group in editing charges?

**Comment by adamsaghy** [comment]
> Thanks @adamsaghy, I understood wrong. One more doubt, if tax group is selected while creating the charges,are we allowed to change the tax group in editing charges?

Yes, of course. You are allowed to change it.

**Comment by adamsaghy** [comment]
> > Thanks @adamsaghy, I understood wrong. One more doubt, if tax group is selected while creating the charges,are we allowed to change the tax group in editing charges?
> 
> Yes, of course. You are allowed to change it.

Seems i was wrong and once the tax group is selected, you are not allowed to modify!

**Pull request closed without merging**
