### PR TITLE
Family added

### PR DESCRIPTION
**Pull request by vatsal3333**
## Description
I have added the option to view family members of a client in this pr.

## Related issues and discussion
#262

## Screenshots, if any
image
image

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] If you have multiple commits please combine them into one commit by squashing them.

- [x] Read and understood the contribution guidelines at `web-app/.github/CONTRIBUTING.md`.

### CODE REVIEW

**Comment by vatsal3333** [comment]
> @vatsal3333 Please fix the travis error.

Done! @luckyman20

**Comment by luckyman20** [comment]
Squash the commits.

**Comment by luckyman20** [comment]
Follow the Commit Style Guidelines.

**Comment by abhaychawla** [comment]
@vatsal3333 If you are still working on this, please update your PR or it will be closed due to inactivity.

**Comment by abhaychawla** [comment]
Closing due to inactivity.

**Pull request closed without merging**
