### PR TITLE
Solution for TranslateModule not exported from SharedModule #1304

### PR DESCRIPTION
**Pull request by nestorlazcano-fintecheando**
## Description
Fixed implementation of translated because it is not working correctly

## Related issues and discussion
#1304

### English
image

### French
image

### CODE REVIEW

**Comment by bharathcgowda** [comment]
Looks ok to me, @BLasan  could you help us by reviewing the code?
@nestorlazcano  can you review why the checks have failed?

**Review by Jov03 — CHANGES_REQUESTED** [review]
@nestorlazcano-fintecheando your changes look good to me but your PR contains changes for other issues as well. So can you update your PR with a single commit containing changes to resolve this issue only?

Also please resolve all linting errors as well so that all GitHub checks pass.

**Comment by nestorlazcano-fintecheando** [comment]
Thank you, I will send my new PR

**Comment by nestorlazcano-fintecheando** [comment]
## I already sent the new PR 
https://github.com/openMF/web-app/pull/1355

**Pull request closed without merging**
