### PR TITLE
refactoring of webapp to consume typesript client

### PR DESCRIPTION
**Pull request by PC-11-00**
## Description
added fineract-client autogenerated services code copying from backend which were generated, these will replace custom services to autogenerated services

## Related issues and discussion
#{Issue Number}

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] If you have multiple commits please combine them into one commit by squashing them.

- [x] Read and understood the contribution guidelines at `web-app/.github/CONTRIBUTING.md`.

### CODE REVIEW

**Comment by Thanush66** [comment]
Hii could you please contact me in the mail saithanushreddy66@gmail.com

**Comment by PC-11-00** [comment]
@Thanush66 This is not a proper way to contact, you should not comment unnecessary comments on the PRs, there is a proper a slack channel for the conversations : https://mifos.org/resources/community/communications/

**Comment by Thanush66** [comment]
Okay! I pinged you on the slack channel

**Comment by adamsaghy** [comment]
@PC-11-00 This is a huge PR! i am not sure what to do with this. Is there a way to do it in smaller pieces?

**Comment by PC-11-00** [comment]
@adamsaghy Actually these are autogenerated Rest APIs files, so this can't be in smaller pieces. 
Firstly these files will be merged then only I will change custom APIs with these autogenerated API files 
@vidakovic knows everything about them

**Pull request closed without merging**
