### PR TITLE
feat: add charges component

### PR DESCRIPTION
**Pull request by jonathanzhang53**
## Description
Implemented charges component. It is a bit different from community-app screen. I made the Is Penalty? into red/green circles with checks/times for yes/no. I made the status into red/green circles.

## Related issues and discussion
187

## GIF
charges
There are a few visual errors with the circles in the gif, but they do not occur when testing on machine.
image

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] If you have multiple commits please combine them into one commit by squashing them.

- [x] Read and understood the contribution guidelines at `web-app/.github/CONTRIBUTING.md`.

### CODE REVIEW

**Comment by jonathanzhang53** [comment]
@abhaychawla got it. changes coming.

**Comment by jonathanzhang53** [comment]
@abhaychawla finished changes and build exited. updated gif.

**Comment by jonathanzhang53** [comment]
@abhaychawla are u sure? I thought it would close the issue, same one as before

**Comment by abhaychawla** [comment]
It closes the issue if you specify a keyword like fix or close along with it.

**Comment by jonathanzhang53** [comment]
@abhaychawla got it. thanks.

**Pull request merged**
