### PR TITLE
feat: add edit template component

### PR DESCRIPTION
**Pull request by BLasan**
## Description
Added Edit Template component to edit selected templates.
Installed CKEditor5.

Commands: 
 1) npm install --save @ckeditor/ckeditor5-angular
 2) npm install --save @ckeditor/ckeditor5-build-classic

## Related issues and discussion
#702 

## Screenshots, if any
web-app4

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] If you have multiple commits please combine them into one commit by squashing them.

- [x] Read and understood the contribution guidelines at `web-app/.github/CONTRIBUTING.md`.

### CODE REVIEW

**Comment by spider0061** [comment]
@BLasan build tests are failing. Please, have a look.

**Comment by BLasan** [comment]
> @BLasan build tests are failing. Please, have a look.

Should I add package.json and package-lock.json files? I added new dependency for the html editor

**Comment by spider0061** [comment]
> > @BLasan build tests are failing. Please, have a look.
> 
> Should I add package.json and package-lock.json files? I added new dependency for the html editor

If you have added a new dependency like you have added ckeditor here then you have to include package.json.

**Comment by BLasan** [comment]
@abhaychawla  Please review this

**Comment by Rishabh106** [comment]
@BLasan You should change the PR Title and commit message to `feat: add edit template component` because it is a commit message convention as stated [here](https://github.com/openMF/web-app/blob/master/.github/COMMIT_MESSAGE.md#subject)

**Comment by BLasan** [comment]
> @BLasan You should change the PR Title and commit message to `feat: add edit template component` because it is a commit message convention as stated [here](https://github.com/openMF/web-app/blob/master/.github/COMMIT_MESSAGE.md#subject)

Yuh. I'll change the PR title and commit message

**Comment by karantakalkar** [comment]
@BLasan Quite a few changes may be required and we have less time I'll coauthor you for edit template.

**Pull request closed without merging**
