### PR TITLE
fix: login form validation errors after submitting form

### PR DESCRIPTION
**Pull request by AashishChakravarty**
## Description
i have update angular form validation method `model-driven approach` to `template-driven approach` Now it does not show validation errors after submitting form.

## Related issues and discussion
#655 

## Screenshots, if any
image

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] If you have multiple commits please combine them into one commit by squashing them.

- [x] Read and understood the contribution guidelines at `web-app/.github/CONTRIBUTING.md`.

### CODE REVIEW

**Comment by karantakalkar** [comment]
template-driven forms are not utilized anywhere in the app, only reactive forms are meant to be used

**Comment by AashishChakravarty** [comment]
@karantakalkar yes i know but in template-driven easy to data handling.

**Comment by abhaychawla** [comment]
@AashishChakravarty we won't be changing the approach to template-driven forms.

**Comment by AashishChakravarty** [comment]
@abhaychawla Now I fixed this issue with model-driven approach

**Comment by karantakalkar** [comment]
It is important to reset login form post login, we won't change the code just to get rid of validation errors, also as per comment clearance of validation errors is an angular material bug.

**Pull request closed without merging**
