### PR TITLE
fix: added translation changes

### PR DESCRIPTION
**Pull request by PC-11-00**
## Description
Now we can see the Client Approval, actually translation spelling was wrong so Html file was not loading and added few more translation changes

## Screenshots, if any

https://github.com/openMF/web-app/assets/76156941/16aa207f-9e1a-416d-9283-6fb1af135ab0

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] If you have multiple commits please combine them into one commit by squashing them.

- [x] Read and understood the contribution guidelines at `web-app/.github/CONTRIBUTING.md`.

### CODE REVIEW

**Comment by bharathcgowda** [comment]
@adamsaghy  could you please help us in reviwing this PR?

**Comment by adamsaghy** [comment]
@PC-11-00 @bharathcgowda I see no other changes but code format changes and extra translations. Is there anything i am missing?

**Comment by PC-11-00** [comment]
No @adamsaghy, only translations changes

**Comment by adamsaghy** [comment]
> No @adamsaghy, only translations changes

Would you be so kind to state rename the PR title, PR description and commit message accordingly? It is pretty misleading now...

**Comment by PC-11-00** [comment]
@adamsaghy yeah okay, actually I was working on this(maker-checker) issue, and by mistake I forgot to change the name sorry

**Pull request merged**
